development:
  secret_key_base: super_long_secret_key_for_development
  google_client_id: 379998383314-pel85o9sf5r707d4nv558huloavqmg3m.apps.googleusercontent.com
  google_client_secret: Lq-jbqbReewD5msK4b8Qwf5j
